src/Entity/Property.php
<?php


namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @Vich\Uploadable
 */
class Property
{

    const HEAT = [
        0 => 'electric',
        1 => 'gaz'
    ];

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     * @var string
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="properties", fileNameProperty="image")
     * @var File
     */
    private $imageFile;


    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5,max=15)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\Length(min=5,max=15)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     */
    private $floor;

    /**
     *
     * @ORM\Column(type="integer")
     * @Assert\Positive
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Positive
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

     /**
     * @ORM\Column(type="datetime",nullable=true)
     * @var \DateTime
     */
    private $updatedAt;


    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getImage()
    {
        return $this->image;
    }

}

templates/base.html.twig
<html lang="en">
<head>
  {{ include('include/header.html.twig') }}
  <title>{% block title %} {% endblock %}</title>
        {% block stylesheets %}{% endblock %}
</head>
<body>
 <!-- menu -->
 {{ include('menu/menu.html.twig') }}

  <div class="section no-pad-bot" id="index-banner">
    <!-- container -->
    <div class="container">
      <br><br>
      
      <!-- body -->
      <div class="row center">
       {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
      </div> 
        <br>
    </div>
  </div>
   
   <!-- footer -->
   {{ include('include/footer.html.twig') }}
   {{ include('include/scripts.html.twig') }}
  </body>
</html>

templates/home.html.twig
{% extends 'base.html.twig' %}


{% block title %} 
 Home
{% endblock %}

{% block body %}

<!-- search -->
<div class="row">
    <div class="col s12 m12">
      <div class="card green darken-1">
        <div class="card-content white-text">
          <span class="card-title">Search properties for sale and to rent</span>
          <p>{{ form_start(form) }}
             {{ form_widget(form) }}
            <input type="submit" class="btn" value="Start" />
            {{ form_end(form) }}
          </p>
        </div>
      </div>
    </div>
  </div>
<br>


<div class="row">
    {% for property in properties %}
        <div class="col s12 m4">
            <div class="card">
                
                <!-- image -->
                <div class="card-image">
                {% if property.image %}
                <img src="/images/properties/{{property.image}}" height="200" />
                {% else %}
                <img src="/images/logo-building.png" height="200">
                {% endif %}
                </div>

                <!-- title + price -->
                <div class="card-content">
                <p>
                <h5>{{property.title}}</h5>
                <p> {{property.price}} €</p>
                </p>
                </div>

                <!-- view -->
                <div class="card-action">
                <a href="{{ path('show', {'id': property.id}) }}" class="waves-effect waves-light btn">Voir plus</a>
                </div>


            </div>
        </div>
    {% endfor %}

</div>

<!-- pagination -->
<br>
{{ knp_pagination_render(properties) }}
{% endblock %}

templates/properties.html.twig
{% extends 'base.html.twig' %}

{% block title %} Our Properties {% endblock %}

{% block body %}

<div class="row">
    
    {% for property in properties %}
        <div class="col s12 m4">
            <div class="card">

                <!-- img -->
                <div class="card-image">
                {% if property.image %}
                <img src="/images/properties/{{property.image}}" height="200" />
                {% else %}
                <img src="/images/logo-building.png" height="200">
                {% endif %}
                </div>

                <!-- title + price -->
                <div class="card-content">
                <p>
                <h5>{{property.title}}</h5>
                <p>{{property.price}} €</p>
                </p>
                </div>

                <!-- view button -->
                <div class="card-action">
                <a href="{{ path('show', {'id': property.id}) }}" class="waves-effect waves-light btn" >Voir plus</a>
                </div>

                
            </div>
        </div>
    {% endfor %}

</div>
<br>
{{ knp_pagination_render(properties) }}
{% endblock %}

templates/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{property.title}}  {% endblock %}

{% block body %}

  <!-- style -->
  <style type="text/css">
  #detail_item{
    color: rgba(238, 110, 115, 0.7);
    font-size: 14px;
    text-overflow: ellipsis;
    overflow: hidden;
    -webkit-transition: color .28s ease, background-color .28s ease;
    transition: color .28s ease, background-color .28s ease;
  }

</style>

  <!-- message -->
  {% for message in app.flashes('info') %}
      <div style=" border-color: #0288d1;background-color: #29b6f6;color: white; width:100%;
    border: 1px solid;padding:10px;margin: 20px;color: white;">
          {{ message }}
      </div>
  {% endfor %}



 <div class="card">
    <div class="card-content">

    <!-- image + title -->
    <p>
            {% if property.image %}
            <img src="/images/properties/{{property.image}}" height="400" width="400" />
            {% else %}
            <img src="/images/logo-building.png" height="400" width="400">
            {% endif %}
     </p>       
          <h2>{{property.title}}</h2>
    </div>


    <div class="card-tabs">
      <ul class="tabs tabs-fixed-width">
        <li class="tab"><a class="active" href="#test4">information</a></li>
        <li class="tab"><a  href="#test5">Contact</a></li>
      </ul>
    </div>
    <div class="card-content grey lighten-4" style="text-align: left;">

     <!-- details -->
      <div id="test4">
      <p>
       <div >  <p class="flow-text"> <i class="material-icons">book</i> Description : </p> {{property.description}}</div><br>
      <div> <p class="flow-text"><i class="material-icons">home</i> Rooms :</p> {{property.rooms}}</div><br>
      <div>  <p class="flow-text"> <i class="material-icons">format_shapes</i> Surface :</p>{{property.surface}} m²</div><br>
      <div>  <p class="flow-text"><i class="material-icons">confirmation_number</i> Bedroomds :</p>{{property.bedrooms}}</div><br>
      <div>  <p class="flow-text"><i class="material-icons">attach_money</i>Price : </p> {{property.price}} €</div><br>
      <div>  <p class="flow-text"><i class="material-icons">business</i> Floor : </p>{{property.floor}}</div><br>
      <div>  <p class="flow-text"><i class="material-icons">location_city</i> City : </p>{{property.city}}</div><br>
      <div>  <p class="flow-text"><i class="material-icons">location_on</i> Address : </p>{{property.address}}</div><br>
      <div>  <p class="flow-text"><i class="material-icons">local_post_office</i> Postal Code :</p>{{property.postalCode}}</div><br>
      </p>
      </div>
      
      
      <!-- contact form -->
      <div id="test5">
      <br><br>
      {{ form_start(form) }}
      {{ form_widget(form) }}
      <br>
      <input type="submit" class="btn" value="Contact" />
      {{ form_end(form) }}
      </div>



    </div>
  </div>

{% endblock %}